"""initial migration

Revision ID: 1da5b6241d4b
Revises: d75f297cb88
Create Date: 2015-04-20 16:24:06.918000

"""

# revision identifiers, used by Alembic.
revision = '1da5b6241d4b'
down_revision = 'd75f297cb88'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
