"""initial migration

Revision ID: 23e9b8886662
Revises: 45c803bec109
Create Date: 2015-04-17 14:01:10.117000

"""

# revision identifiers, used by Alembic.
revision = '23e9b8886662'
down_revision = '45c803bec109'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
